import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { Manual, manuals } from "./api/hello";

const SingleManualLink = (manualData: Manual) => (
  <li>
    <Link href={`/manuals/${manualData.link}`}>
      <a className={styles.link}>
        {manualData.name}
      </a>
    </Link>
    <aside className={styles.details}>
      <ul className={styles.languages}>
        {manualData.languages.map(language => <li key={language} title="Instrukcja dostępna w języku polskim">{language}</li>)}
      </ul>
      <a
        href={manualData.pdfFileUrl}
        className={styles.fileDownload}
        title="Kliknij, aby pobrać plik PDF"
      >
        <svg
          version="1.1"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 287 287"
        >
          <g>
            <path
              d="M137.941,147.788c1.551,2.213,3.88,3.482,6.391,3.482c2.51,0,4.839-1.269,6.39-3.482l40.346-57.586
      c1.683-2.402,1.976-4.982,0.785-7.27c-1.191-2.287-3.653-3.432-6.586-3.432H165V24.51c0-4.963-3.244-9.01-8.207-9.01h-24.914
      c-4.963,0-8.879,4.047-8.879,9.01V79.5h-19.6c-2.934,0-5.396,1.146-6.587,3.436c-1.19,2.288-0.896,4.979,0.787,7.38
      L137.941,147.788z"
            />
            <path
              d="M287,199.5c0-7.18-5.82-13-13-13H13c-7.18,0-13,5.82-13,13v59c0,7.18,5.82,13,13,13h261c7.18,0,13-5.82,13-13V199.5z
      M58,244.5H19v-31h39V244.5z M113,244.5H74v-31h39V244.5z"
            />
          </g>
        </svg>
      </a>
    </aside>
  </li>
);

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.root}>
        <h1 className={styles.title}>Instrukcje PDF</h1>
        <ul className={styles.list}>
          {manuals.map((singleManual: Manual) => <SingleManualLink key={singleManual.link} {...singleManual} />)}
        </ul>
        <footer className={styles.footer}>&copy; 2022;</footer>
      </section>
    </>
  );
};

export default Home;
